20760540: Footer Component
PRGH-GH/skillchain-landingpage pull request #23
Opened 2023-02-22 15:18 UTC by naomiinanna

2023-02-23 06:07 UTC, Aiyanna1 reviewed
I'm not one hundred percent sure but I think the class names need to start with a capital letter

2023-02-23 08:46 UTC, Aiyanna1 commented on src/components/components/Footer/Footer.scss
> +
I don't think these spaces within the footer are needed.

2023-02-23 08:46 UTC, Aiyanna1 commented on src/components/components/Footer/Footer.scss
> +
This space as well

2023-02-23 08:46 UTC, Aiyanna1 commented on src/components/components/Footer/Footer.js
> +                    <a classname='privacy__policy' href='#'>Privacy Policy</a>
There is a little typo in classname here, should be className

2023-02-23 08:46 UTC, Aiyanna1 commented on src/components/components/Footer/Footer.js
> +            <div className='Footer__container'>
would a footer element be better suited than a div?

2023-02-23 15:20 UTC, anna-bc requested changes, later dismissed

2023-02-23 15:20 UTC, anna-bc commented on src/components/components/Footer/Footer.js
> +                <div className='frame'>
please change to a better className with BEM

2023-02-23 15:20 UTC, anna-bc commented on src/components/components/Footer/Footer.scss
> +        color: #FFFFFF;
change to global color variable (--color-white)

2023-02-23 15:20 UTC, anna-bc commented on src/components/components/Footer/Footer.scss
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
you can remove this import, as the font is already imported in the global stylesheet

2023-02-23 15:20 UTC, anna-bc commented on src/components/components/Footer/Footer.scss
> +@import url('https://fonts.googleapis.com/css2?family=Inter&family=Open+Sans&display=swap');
change this import to only import the 'Open Sans' font

2023-02-23 15:20 UTC, anna-bc commented on src/components/components/App/App.js
> +export default App;
please revert this file to the original state (from main branch), as it would lead to merge conflicts otherwise

2023-02-23 15:20 UTC, anna-bc commented on src/index.js
>  root.render(
please revert this file to the original state (from main branch), as it would lead to merge conflicts otherwise

2023-02-24 08:19 UTC, SKamesiepo approved these changes

2023-02-24 08:20 UTC, RavLiya approved these changes

2023-02-24 08:22 UTC, Star4ze approved these changes

2023-02-24 08:22 UTC, amindu00 commented on src/components/components/Footer/Footer.js
> +                    <a classname='privacy__policy' href='#'>Privacy Policy</a>
classname =>className

2023-02-24 08:22 UTC, timmy38233 approved these changes

2023-02-24 08:24 UTC, jasper-prgh approved these changes

2023-02-24 08:26 UTC, merged

2023-02-24 08:33 UTC, tinkabel85 commented on src/components/components/Footer/Footer.scss
> +            align-items: center;
as per design, all items in footer section are aligned to the left side (flex-start) in mobile view